# Generated by Django 4.1 on 2022-08-23 12:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(max_length=13)),
                ('birth_date', models.DateField(help_text='YYYY-MM-DD')),
                ('gender', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='og.artist')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('starting_date', models.DateField(help_text='YYYY-MM-DD')),
                ('ending_date', models.DateField(help_text='YYYY-MM-DD')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='og.artist')),
            ],
            options={
                'db_table': 'exhibitions',
            },
        ),
        migrations.CreateModel(
            name='ArtistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(max_length=13)),
                ('birth_date', models.DateField(help_text='YYYY-MM-DD')),
                ('gender', models.CharField(max_length=4)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artist_entries',
            },
        ),
    ]
