# Generated by Django 4.1 on 2022-08-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('og', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='og.exhibition')),
            ],
            options={
                'db_table': 'exhibition_items',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='exhibition_item',
            field=models.ManyToManyField(related_name='ex_item', through='og.ExhibitionItem', to='og.exhibition'),
        ),
        migrations.AddField(
            model_name='exhibitionitem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='og.item'),
        ),
    ]
