# Generated by Django 4.1 on 2022-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('og', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='exhibition_item',
            field=models.ManyToManyField(related_name='ex_item', through='og.ExhibitionItem', to='og.exhibition'),
        ),
    ]
