# Generated by Django 4.1 on 2022-08-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('og', '0002_exhibition_exhibition_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='name',
            new_name='exhibition_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
    ]
