# Generated by Django 4.1 on 2022-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('og', '0003_rename_name_exhibition_exhibition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistentry',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
    ]
